### ISSUE TITLE
Consuming library in UI5 typescript project

### ISSUE THREAD

**Issue by luboslav** [ui5-community/generator-ui5-ts-library#17]
Hi, I am trying to develop and consume typescript lib generated via your generator.

I have successfully generated and publish lib to private NPM package registry. But I haven't found any tutorial how to integrate it in UI5 application. The application is generated with typescript [generator](https://github.com/ui5-community/generator-ui5-ts-app).

So far I have installed library as dependency via NPM. Do you have any example repository or guide for this scenario?

Any help would be highly appreciated. 

Thanks

**Comment by petermuessig** [comment]
A small tutorial can be found here:
https://github.com/petermuessig/typescript-app-and-lib-plus-npm-packages
