### ISSUE TITLE
Running the package.json watch script fails because of missing tsconfig.json types array

### ISSUE THREAD

**Issue by Zuns** [ui5-community/generator-ui5-ts-library#2]
Hi team,

**Issue:**
Running `yarn watch` fails with the following: 
Error: Type 'Control' referenced in path-to-my-library/src/use/ui5/library/Example.ts could not be resolved - are the UI5 (and other) type definitions available and known in the tsconfig? Or is there a different reason why this type would not be known?

**Fix:**
File: generator-ui5-ts-library/generators/app/templates/tsconfig.json
Add: `"types": ["<%= tstypes %>"],` under the `"baseUrl": "./",` line
Why: After manually adding `"types": ["@sapui5/ts-types-esm"],`  to the generated tsconfig.json file, the `yarn watch` command executed successfully.

Friendly regards,
Zühnja

**Comment by lemaiwo** [comment]
Thanks for letting us know. The template is based on the example repo https://github.com/SAP-samples/ui5-typescript-control-library maintained by @akudev .
@akudev , what do you think? Do we need to adapt this into the template for Yarn or is there another way to solve this?

**Comment by akudev** [comment]
@lemaiwo the mentioned sample repo is different in this respect: it uses the OpenUI5 types from the default "@types" namespace (via DefinitelyTyped). This reduces the need for configuration, as these types are picked up automatically.
But the SAPUI5 types are not published there, so in this yeoman template you went for `@sapui5/ts-types-esm`/`@openui5/ts-types-esm`, which requires the additional [typeRoots config](https://github.com/ui5-community/generator-ui5-ts-library/blob/main/generators/app/templates/tsconfig.json#L16). 

However, that config should be sufficient and everything should work well. Adding "types" settings means that global typings from all other types are not available. E.g. for the global "jQuery" object - unless "jQuery" is also added to the "types". This is why in the sample apps we [recently went back](https://github.com/ui5-community/generator-ui5-ts-app-fcl/issues/5#issuecomment-1200994227) to only using the "typeRoots" settings.

And essentially, after overcoming two new unrelated issues I just reported, I have no problems with `yarn start` or `yarn watch`. So I'm not sure why one would then encounter such an issue.

@Zuns :
Can you check the "typeRoots" settings in `tsconfig.json` and the ".../ts-types-esm" dependency line in `package.json`?
Can you check whether the types are properly available in `node_modules` and/or re-run `npm i`/ `yarn`?
Can you check the easy-UI5 version ( `npm info generator-easy-ui5 version`) and the yeoman version?

(By the way, yarn is one of the recommendations to use, but the template itself runs essentially `npm i`, resulting in an npm `package-lock.json` file, which causes warnings when running `yarn` later. Not sure whether this can lead to other trouble.)

**Comment by akudev** [comment]
@Zuns Also, I'm a bit puzzled why you did not encounter https://github.com/ui5-community/generator-ui5-ts-library/issues/3 and https://github.com/ui5-community/generator-ui5-ts-library/issues/4
Or did you?

If not, would you be so kind and also let me know the versions of easy-ui5 and yeoman-generator? 
The very beginning of the output of the following commands will do (it should say something like "yeoman-generator@5.7.0" or a different version number):
`npm info yeoman-generator`
`npm info generator-easy-ui5`

**Comment by Zuns** [comment]
Hi @akudev 

**Type array vs typeRoots:**
-------
**Your question:** 
Adding "types" settings means that global typings from all other types are not available. E.g. for the global "jQuery" object - unless "jQuery" is also added to the "types". This is why in the sample apps we https://github.com/ui5-community/generator-ui5-ts-app-fcl/issues/5#issuecomment-1200994227 to only using the "typeRoots" settings.
**My answer:** 
I'm new to tsconfig and the "fix" I mentioned above helped to get me going. I assumed that it might help someone else as well. Thanks for explaining. I'm glad that it isn't actually necessary.

**My version info**:
--------
![Versions](https://user-images.githubusercontent.com/10627889/182836651-20771ff8-3e39-4557-bf20-59507db17b6c.jpg)
Running `npm info yeoman-generator` gave:
yeoman-generator@5.7.0

**Tickets #3 and #4:**
----------
**Your question:** 
Also, I'm a bit puzzled why you did not encounter [#3](https://github.com/ui5-community/generator-ui5-ts-library/issues/3) and [#4](https://github.com/ui5-community/generator-ui5-ts-library/issues/4)
**My answer:** 
#3: I started with `yo easy-ui5` to see which options are available and then selected `ts-library`. 
#4: I encountered the following during generation and then read the Readme which stated to run `npm i` which seemed to work and I hoped that it fixed whatever install step broke during generation.:
![Error and npm i](https://user-images.githubusercontent.com/10627889/182838105-15947d99-5119-4681-bbf2-78ba93664873.jpg)
The Readme's next step is to run `npm run watch` which gives this error:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/10627889/182838691-c6eeff0a-036b-49eb-bcba-86dc992ce173.png">

**Comment by akudev** [comment]
Hi @Zuns 
Thanks a lot for your help!

You avoided issue #3 by manually selecting the right thing and #4 did hit you, but you found a way out. This is good to know, so the behavior is consistent with my expectations (I have the same versions of everything, so a different behavior would be strange) and my fixes for both issues are the right thing to do and will help others.

Unfortunately this is where consistency ends: the error you get with `npm run watch` is not reproducible on my side. It is apparently thrown [here](https://github.com/SAP/ui5-typescript/blob/307680ecce7531284d918f6bb8e25780e8d4a23d/packages/ts-interface-generator/src/interfaceGenerationHelper.ts#L116) while looking at the inheritance clause in [this line](https://github.com/ui5-community/generator-ui5-ts-library/blob/main/generators/app/templates/src/baselibrary/Example.ts#L25).
So when I say "it's not needed" then this statement is apparently wrong for your machine.

I noticed that on your machine the `@ui5/ts-interface-generator` is in `/workspaces/ui5-dev-env/node_modules`, several folders above `/workspaces/ui5-dev-env/projects_and_libs/library/node_modules`, where I would have expected it. In which of these folders is the `@openui5` or `@sapui5` folder containing `ts-types-esm`?

The fix you proposed is not a bad thing and if it unblocks you: go for it!
If someone else with the same problem reads this: try it!
Just keep in mind that you'll then have to add other type packages explicitly to the same "types" list in case you want to access them globally (the types for every module that is `import`ed should still work).

**Comment by akudev** [comment]
Addition regarding my question
> In which of these folders is the @openui5 or @sapui5 folder containing ts-types-esm?

If these type definions are in the same (upper) `node_modules` folder as the `@ui5/ts-interface-generator`, then it's obvious why the typeRoots settings don't work: they reference a different location (the "lower" `node_modules` folder which is a sibling of `tsconfig.json`):

```ts
        "typeRoots": [
            "./node_modules/@types",
            "./node_modules/<%= tstypes %>"
        ],
```

In this case the remaining question would be why they went to this upper `node_modules` folder. Maybe you invoked `yarn` (or `npm install`) directly inside `/workspaces/ui5-dev-env` after the initial failure?

_EDIT: I cannot easily get the dependencies installed some folders above and still launch `yarn watch`. Nevertheless I assume the type definitions are only up there. A `yarn` call inside the directory where the `tsconfig.json` file resides might fix things. And you might also want to re-try `yo easy-ui5 ts-library` now (my two fixes have been merged), so the "install" is hopefully succeeding automatically._

**Comment by Zuns** [comment]
Hi @akudev, 

Yes, for me the @types and **@sapui5/ts-types-esm** packages are both in the workspace's node_modules. I have a setup like this ([tutorial I followed - not actually for TS versions](https://startup.lwmeta.com/2021/04/06/how-to-consume-ui5-custom-libraries-in-bas-or-vs-code/)):
![image](https://user-images.githubusercontent.com/10627889/182887568-aee074f9-2d80-40c4-aa1e-b1acae11c2d2.png)


So in my case I can either use:
````
        "typeRoots": [
            "../../node_modules/@types",
            "../../node_modules/@sapui5/ts-types-esm",
        ],
````
OR:
````
        "types": [
            "@types",
            "@sapui5/ts-types-esm",
            //other global types
        ],
````
Since there is a chance that some of my teammates might not have the same setup and might have their type packages in other node_modules I'm going to test option 2 for a while.


Thanks so much for the help and sharing [this link](https://github.com/ui5-community/generator-ui5-ts-app-fcl/issues/5) - super helpful. I'll close the ticket.

**Comment by akudev** [comment]
@Zuns Thanks a lot for all the input!

So in general, due to previous setup, the node_modules folder can reside somewhere else than expected by the template, so the typeRoots paths are wrong. Not sure what could be done in the template except a hint what to look out for when facing the error.
It's up to @lemaiwo etc. to think about this.

For sure the ts-interface-generator, which throws the error, could be more verbose in this situation and check whether there are any type definitions at the location specified in the tsconfig it is using. I opened https://github.com/SAP/ui5-typescript/issues/375 to not forget about this.


(By the way: the article you linked seems to be just a copy, and I would say: one with errors compared to the original. The original is at https://blogs.sap.com/2021/04/06/how-to-consume-ui5-custom-libraries-in-bas-or-vs-code/)

**Comment by lemaiwo** [comment]
I mentioned it in the readme just beneath the npm run watch step
